### ISSUE TITLE
testing fails on Windows

### ISSUE THREAD

**Issue by csm10495** [pytest-dev/pytest-html#336]
Running unit tests fails on Windows:

testing/test_pytest_html.py::TestHTML::test_utf8_longrepr[u'\x81'] FAILED             
and
testing/test_pytest_html.py::TestHTML::test_report_display_utf8 FAILED

I wonder if we can/should skip these tests on Windows or modify them in some way.

**Comment by csm10495** [comment]
Stuff like: 
```
    def decode(self, input, final=False):
>       return codecs.charmap_decode(input,self.errors,decoding_table)[0]
E       UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 11022: character maps to <undefined>
```

**Comment by csm10495** [comment]
It has to do with a different default encoding used on windows/*nix type systems in Python.

When using Windows Python, we get an error, though in bash on WSL it works fine: 
```
PS C:\Users\csm10495\Desktop\pytest-html> python
Python 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> with open('test', 'w') as f: f.write(u'\u0081')
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\x81' in position 0: character maps to <undefined>
>>> exit()
PS C:\Users\csm10495\Desktop\pytest-html> bash                                                csm10495@csm10495-laptop:/mnt/c/Users/csm10495/Desktop/pytest-html (master) $ python3
Python 3.8.2 (default, Jul 16 2020, 14:00:26)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> with open('test', 'w') as f: f.write(u'\u0081')
...
1
>>> exit()
```

... odd

**Comment by csm10495** [comment]
Looks like the preferred encoding used by python is different in windows/*nix:
```
PS C:\Users\csm10495\Desktop\pytest-html> python                                              Python 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> locale.getpreferredencoding(False)
'cp1252'
>>> exit()
PS C:\Users\csm10495\Desktop\pytest-html> bash                                                pcsm10495@csm10495-laptop:/mnt/c/Users/csm10495/Desktop/pytest-html (master) $ python3
Python 3.8.2 (default, Jul 16 2020, 14:00:26)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> locale.getpreferredencoding(False)
'UTF-8'
>>>       
```

**Comment by csm10495** [comment]
We could swap from using pytest directly to:
```
python -X utf8 -m pytest
```
though that only exists in py3.7 and later (https://www.python.org/dev/peps/pep-0540/)... wonder if there is a way to fix 3.6 too.

**Comment by gnikonorov** [comment]
Hi @csm10495. I've assigned you as it looks like you have an open PR that closes this. Please let me know if I incorrectly assigned to you and I'll remove you as an assignee.

**Comment by csm10495** [comment]
Hey @gnikonorov , all good. Let me know if the PR can be signed off on to close out :)

**Comment by gnikonorov** [comment]
Thank you @csm10495! I'll check later tonight

**Comment by gnikonorov** [comment]
@csm10495 [this](https://github.com/pytest-dev/pytest-html/pull/337) is the PR right? If so can you update the title to reference the proper issue? It looks like right now it's closing [335](https://github.com/pytest-dev/pytest-html/pull/335), which I don't think is right

**Comment by csm10495** [comment]
oh dear. That is a flub.

**Comment by csm10495** [comment]
Fixed it in the PR title. I'm not sure if I should rewrite history to fix the comment... don't want to mess anything up. Think its ok to do? @gnikonorov

**Comment by gnikonorov** [comment]
@csm10495 i think if you rebase and reword the first commit it should be fine

**Comment by gnikonorov** [comment]
Worst case you could always open a new PR and reference the original in your description if you don't want to mess up the history

**Comment by gnikonorov** [comment]
This was fixed by https://github.com/pytest-dev/pytest-html/pull/357, thank you @csm10495!

**Comment by gnikonorov** [comment]
Closing, since the change is in master. Please reopen if I closed this incorrectly

**Comment by mar10** [comment]
This bug still occurs here running on Windows 11, inside VSCode Terminal and Windws-Terminal (PowerShell).
Please reopen.

```
pytest                        7.3.1
pytest-cov                    4.0.0
pytest-html                   3.2.0
pytest-metadata               2.0.4
```
running
```py
pytest --cov --html=report.html --self-contained-html
```

It seems that the html content is generated as UTF-8, but the target file is opened with Cp1252 encoding.
(No encoding arg is passed to `Path.write_text()`)

```py
    def _save_report(self, report_content):
        dir_name = self.logfile.parent
        assets_dir = dir_name / "assets"

        dir_name.mkdir(parents=True, exist_ok=True)
        if not self.self_contained:
            assets_dir.mkdir(parents=True, exist_ok=True)

        self.logfile.write_text(report_content)
```

Results in 
```ps1
tests\test_wsgidav_app.py .....                                                                                                                                                   [100%]Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\marti\.virtualenvs\wsgidav-cVfCLppo\Scripts\pytest.exe\__main__.py", line 7, in <module>
  File "C:\Users\marti\.virtualenvs\wsgidav-cVfCLppo\Lib\site-packages\_pytest\config\__init__.py", line 189, in console_main
    code = main()
           ^^^^^^
  File "C:\Users\marti\.virtualenvs\wsgidav-cVfCLppo\Lib\site-packages\_pytest\config\__init__.py", line 166, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\.virtualenvs\wsgidav-cVfCLppo\Lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\.virtualenvs\wsgidav-cVfCLppo\Lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\.virtualenvs\wsgidav-cVfCLppo\Lib\site-packages\pluggy\_callers.py", line 60, in _multicall
    return outcome.get_result()
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\.virtualenvs\wsgidav-cVfCLppo\Lib\site-packages\pluggy\_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\Users\marti\.virtualenvs\wsgidav-cVfCLppo\Lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\.virtualenvs\wsgidav-cVfCLppo\Lib\site-packages\_pytest\main.py", line 316, in pytest_cmdline_main
    return wrap_session(config, _main)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\.virtualenvs\wsgidav-cVfCLppo\Lib\site-packages\_pytest\main.py", line 304, in wrap_session
    config.hook.pytest_sessionfinish(
  File "C:\Users\marti\.virtualenvs\wsgidav-cVfCLppo\Lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\.virtualenvs\wsgidav-cVfCLppo\Lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\.virtualenvs\wsgidav-cVfCLppo\Lib\site-packages\pluggy\_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "C:\Users\marti\.virtualenvs\wsgidav-cVfCLppo\Lib\site-packages\_pytest\terminal.py", line 812, in pytest_sessionfinish
    outcome.get_result()
  File "C:\Users\marti\.virtualenvs\wsgidav-cVfCLppo\Lib\site-packages\pluggy\_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\Users\marti\.virtualenvs\wsgidav-cVfCLppo\Lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\.virtualenvs\wsgidav-cVfCLppo\Lib\site-packages\pytest_html\html_report.py", line 333, in pytest_sessionfinish
    self._save_report(report_content)
  File "C:\Users\marti\.virtualenvs\wsgidav-cVfCLppo\Lib\site-packages\pytest_html\html_report.py", line 259, in _save_report
    self.logfile.write_text(report_content)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python311\Lib\pathlib.py", line 1079, in write_text
    return f.write(data)
           ^^^^^^^^^^^^^
  File "C:\Users\marti\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u2642' in position 65105: character maps to <undefined>
Stopping WsgiDavTestServer... done.
(wsgidav) PS C:\prj\git\wsgidav> 
```

**Comment by BeyondEvil** [comment]
@mar10 Please try 4.0.0rc4

**Comment by mar10** [comment]
Now I get a different error:

```ps1
py311: commands[2]> pip list
Package            Version
------------------ -----------
...
pytest             7.3.1
pytest-cov         4.0.0
pytest-html        4.0.0rc4
pytest-metadata    2.0.4
...
py311: commands[3]> pytest -ra -v -x --cov=wsgidav --durations=10 --html=build/pytest/report-py311.html --self-contained-html
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "C:\prj\git\wsgidav\.tox\py311\Lib\site-packages\_pytest\main.py", line 267, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "C:\prj\git\wsgidav\.tox\py311\Lib\site-packages\pluggy\_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\prj\git\wsgidav\.tox\py311\Lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\prj\git\wsgidav\.tox\py311\Lib\site-packages\pluggy\_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\prj\git\wsgidav\.tox\py311\Lib\site-packages\pluggy\_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "C:\prj\git\wsgidav\.tox\py311\Lib\site-packages\pluggy\_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\prj\git\wsgidav\.tox\py311\Lib\site-packages\pytest_html\basereport.py", line 253, in pytest_sessionstart
INTERNALERROR>     self._generate_report()
INTERNALERROR>   File "C:\prj\git\wsgidav\.tox\py311\Lib\site-packages\pytest_html\selfcontained_report.py", line 36, in _generate_report
INTERNALERROR>     super()._generate_report(self_contained=True)
INTERNALERROR>   File "C:\prj\git\wsgidav\.tox\py311\Lib\site-packages\pytest_html\basereport.py", line 142, in _generate_report
INTERNALERROR>     rendered_report = self._render_html(
INTERNALERROR>                       ^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\prj\git\wsgidav\.tox\py311\Lib\site-packages\pytest_html\basereport.py", line 223, in _render_html
INTERNALERROR>     return self._template.render(
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\prj\git\wsgidav\.tox\py311\Lib\site-packages\jinja2\environment.py", line 1301, in render
INTERNALERROR>     self.environment.handle_exception()
INTERNALERROR>   File "C:\prj\git\wsgidav\.tox\py311\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
INTERNALERROR>     raise rewrite_traceback_stack(source=source)
INTERNALERROR>   File "C:\prj\git\wsgidav\.tox\py311\Lib\site-packages\pytest_html\resources\index.jinja2", line 126, in top-level template code
INTERNALERROR>     {% include "app.js" %}
INTERNALERROR>   File "C:\prj\git\wsgidav\.tox\py311\Lib\site-packages\jinja2\loaders.py", line 218, in get_source
INTERNALERROR>     raise TemplateNotFound(template)
INTERNALERROR> jinja2.exceptions.TemplateNotFound: app.js
py311: exit 3 (0.61 seconds) C:\prj\git\wsgidav> pytest -ra -v -x --cov=wsgidav --durations=10 --html=build/pytest/report-py311.html --self-contained-html pid=20284
.pkg: _exit> python C:\Users\marti\.virtualenvs\wsgidav-cVfCLppo\Lib\site-packages\pyproject_api\_backend.py True setuptools.build_meta __legacy__
  py311: FAIL code 3 (17.52=setup[9.23]+cmd[0.02,7.09,0.56,0.61] seconds)
  evaluation failed :( (17.70 seconds)
```

**Comment by BeyondEvil** [comment]
That is super odd!

How are you installing the plugin?

**Comment by mar10** [comment]
Using tox, I added the line `pip install git+https://github.com/pytest-dev/pytest-html@4.0.0rc4`

```ini
[testenv]
usedevelop = True
extras =
    test
passenv =
    LC_ALL
    LANG
    TRAVIS
    TRAVIS_BRANCH
    TRAVIS_OS_NAME
    TRAVIS_BUILD_ID
deps =
    cheroot
    defusedxml
    Jinja2
    json5
    PyYAML
    pytest
    pytest-cov
    #pytest-remove-stale-bytecode
    pytest-html
    redis
    requests
    webtest
setenv =
    COVERAGE_FILE = build/.coverage.{envname}
commands =
    # Run everything from /tests folder:
    python -V
    pip install git+https://github.com/pytest-dev/pytest-html@4.0.0rc4
    pip list
    pytest -ra -v -x --cov=wsgidav --durations=10 --html=build/pytest/report-{envname}.html --self-contained-html {posargs}
```

**Comment by BeyondEvil** [comment]
That’s probably why. 

Try doing a regular ”pip install pytest-html==4.0.0rc4”

**Comment by mar10** [comment]
Looks better now - thanks

**Comment by sayurionishi** [comment]
Hi, I got the same issue for Windows.
Running pytest using this code
` python -m pytest automated-tests --html=report.html
`
I've used the version that was mentioned above and added it to the requirements.txt
`pytest-html==4.0.0rc4`

Errors I got
`Traceback (most recent call last):
  File "C:\Users\sonishi\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\sonishi\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\sonishi\OneDrive - Planit Test Management Solutions Pty Ltd\Desktop\WORK\turing\flowcell_server\venv\lib\site-packages\pytest\__main__.py", line 5, in <module>        
    raise SystemExit(pytest.console_main())
  File "C:\Users\sonishi\OneDrive - Planit Test Management Solutions Pty Ltd\Desktop\WORK\turing\flowcell_server\venv\lib\site-packages\_pytest\config\__init__.py", line 190, in consol
e_main
    code = main()
  File "C:\Users\sonishi\OneDrive - Planit Test Management Solutions Pty Ltd\Desktop\WORK\turing\flowcell_server\venv\lib\site-packages\_pytest\config\__init__.py", line 167, in main  
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File "C:\Users\sonishi\OneDrive - Planit Test Management Solutions Pty Ltd\Desktop\WORK\turing\flowcell_server\venv\lib\site-packages\pluggy\_hooks.py", line 265, in __call__        
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\Users\sonishi\OneDrive - Planit Test Management Solutions Pty Ltd\Desktop\WORK\turing\flowcell_server\venv\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec      
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\sonishi\OneDrive - Planit Test Management Solutions Pty Ltd\Desktop\WORK\turing\flowcell_server\venv\lib\site-packages\pluggy\_callers.py", line 60, in _multicall     
    return outcome.get_result()
  File "C:\Users\sonishi\OneDrive - Planit Test Management Solutions Pty Ltd\Desktop\WORK\turing\flowcell_server\venv\lib\site-packages\pluggy\_result.py", line 60, in get_result      
    raise ex[1].with_traceback(ex[2])
  File "C:\Users\sonishi\OneDrive - Planit Test Management Solutions Pty Ltd\Desktop\WORK\turing\flowcell_server\venv\lib\site-packages\pluggy\_callers.py", line 39, in _multicall     
    res = hook_impl.function(*args)
  File "C:\Users\sonishi\OneDrive - Planit Test Management Solutions Pty Ltd\Desktop\WORK\turing\flowcell_server\venv\lib\site-packages\_pytest\main.py", line 317, in pytest_cmdline_ma
in
    return wrap_session(config, _main)
  File "C:\Users\sonishi\OneDrive - Planit Test Management Solutions Pty Ltd\Desktop\WORK\turing\flowcell_server\venv\lib\site-packages\_pytest\main.py", line 305, in wrap_session     
    config.hook.pytest_sessionfinish(
  File "C:\Users\sonishi\OneDrive - Planit Test Management Solutions Pty Ltd\Desktop\WORK\turing\flowcell_server\venv\lib\site-packages\pluggy\_hooks.py", line 265, in __call__        
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\Users\sonishi\OneDrive - Planit Test Management Solutions Pty Ltd\Desktop\WORK\turing\flowcell_server\venv\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec      
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\sonishi\OneDrive - Planit Test Management Solutions Pty Ltd\Desktop\WORK\turing\flowcell_server\venv\lib\site-packages\pluggy\_callers.py", line 55, in _multicall     
    gen.send(outcome)
  File "C:\Users\sonishi\OneDrive - Planit Test Management Solutions Pty Ltd\Desktop\WORK\turing\flowcell_server\venv\lib\site-packages\_pytest\terminal.py", line 818, in pytest_sessio
nfinish
    self.config.hook.pytest_terminal_summary(
  File "C:\Users\sonishi\OneDrive - Planit Test Management Solutions Pty Ltd\Desktop\WORK\turing\flowcell_server\venv\lib\site-packages\pluggy\_hooks.py", line 265, in __call__        
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\Users\sonishi\OneDrive - Planit Test Management Solutions Pty Ltd\Desktop\WORK\turing\flowcell_server\venv\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec      
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\sonishi\OneDrive - Planit Test Management Solutions Pty Ltd\Desktop\WORK\turing\flowcell_server\venv\lib\site-packages\pluggy\_callers.py", line 55, in _multicall     
    gen.send(outcome)
  File "C:\Users\sonishi\OneDrive - Planit Test Management Solutions Pty Ltd\Desktop\WORK\turing\flowcell_server\venv\lib\site-packages\pytest_html_reporter\plugin.py", line 294, in py
test_terminal_summary
    live_logs_file.write(message)
  File "C:\Users\sonishi\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\ufffd' in position 184234: character maps to <undefined>
`

Hope you could help me check this issue, thank you

**Comment by BeyondEvil** [comment]
From the look of the output it looks like you're not using this plugin but rather: https://github.com/prashanth-sams/pytest-html-reporter

**Comment by sayurionishi** [comment]
My apologies @BeyondEvil , I tried 2 reporters and the errors got changed when I use the version you mentioned which means your fix worked for the pytest-html plugin. Thank you, I think I just need to remove the other plugin 😊

**Comment by BeyondEvil** [comment]
No worries @sayurionishi.

Hopefully a proper v4.0.0 will be released soon.
