### ISSUE TITLE
pytest-html v3.0.0 extras handling

### ISSUE THREAD

**Issue by fenchu** [pytest-dev/pytest-html#397]
with pytest-html v3.0.0 have how images being stored changed in the extras?

v2.1.1 I use my own ext fixture in conftest.py

```
@dataclass
class Ext:
    screenshots:list = None
    urls:list = None
    _dir_:str = None

    def __str__(self):
        s = []
        for k,v in vars(self).items():
            s.append(f"{k}:{v}")
        return ",".join(s)

    def delete(self):
        for k in list(vars(self).keys()):
            #log.info(f"cleaning {self.__dict__[k]}")
            self.__dict__[k] = None

extras = Ext()


@pytest.fixture(scope="session")
def ext():
    """ storage to pass from test to report, but does not follow scope, so need to clean in subsequent tests """
    global extras
    print(f"using ext fixture:{extras}")
    yield extras
    extras = None
    return extras
```

and in my tests I use the following to clean ext if it is not needed:
```
        if ext:
            ext.delete()
        if ext and not ext._dir_:
            if hasattr(params, 'htmldir'):
                ext._dir_ = params.htmldir
            else:
                ext._dir_ = os.getcwd()
        if ext._dir_ and not os.path.isdir(ext._dir_):
            os.mkdir(ext._dir_)
```

and images are pushed like this to ext:
```
        if ext._dir_:
            fname = ext._dir_ + '/' + sys._getframe().f_code.co_name + '-' + webhost + browser + f"-enterssn.png"
            tools.selenium.savescr(wd, fname, ext, t0=t0)


and in selenium.savescr this is all I do after images has been generated:
```
        if ext:
            if not ext.screenshots:
                ext.screenshots = []
            ext.screenshots.append(fname)
```

with v.2.1.1 if I clean ext fixture ext.screenshots they do not show up:
![pytest-html-v2 1 1](https://user-images.githubusercontent.com/11349883/100879527-d4d96100-34ab-11eb-9379-c2f9a07d721e.jpg)

with v.3.0.0 I'm images are there still:
![pytest-html-v3 0 0](https://user-images.githubusercontent.com/11349883/100879612-eb7fb800-34ab-11eb-864a-760e54ca53e4.jpg)

Please update the documentation on how externals extra should work now. Some debug would be nice.

**Comment by BeyondEvil** [comment]
Sorry that you've had to wait 7 days for an answer @fenchu !

Let me take a look at where we're at.

Have you tried the latest version (3.1.0 as of writing this), as I know there's been a bunch of bug-fixes released.

Could you try that and get back to us? 🙏

**Comment by fenchu** [comment]
Hi sorry for late answer, it is still the same extras not able to delete between tests.
```
pytest==6.2.1
pytest-base-url==1.4.2
pytest-clarity==0.3.0a0
pytest-html==3.1.1
pytest-metadata==1.10.0
pytest-mock==3.3.1
pytest-variables==1.9.0
pytest-watch==4.2.0
```
pytest 6.2.1 and pytest-2.1.1 works fine together

**Comment by fenchu** [comment]
Fixed this by explicitly deleting screenshots from my Ext fixture in pytest_runtest_makereport() after they are pushed to never had to do before pytest-html v3:
```
        while len(ext.screenshots):
            sc = ext.screenshots.pop(0)
            extra.append(pytest_html.extras.image(sc, mime_type='image/png', extension='png'))
```

Also using fixtures in hooks should be implemented. I need to make a global out of the Ext fixture to access it as a global not as a Fixture function.
